name: Continuous Integration

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  format-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}

    - name: Prettify code
      uses: creyD/prettier_action@v2.2
      with:
        # This part is also where you can pass other options, for example:
        prettier_options: --write **/*.{js,md,mdx}

    - name: Lint code
      uses: getsentry/action-eslint-fix@v1
      with:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
